# Site settings
author: Aurora Avery
title: "Hello World!"
header-img: img/home-bg.png
email: aurora.avery@yahoo.com
copyright_name: Aurora Avery
description: > # this means to ignore newlines until "baseurl:"
  ("Hello World" is a first step for learning code)
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  aurora-avery

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
